import type { NextPage } from "next";

import Menu from "../components/menu";
import Pinned from "../components/pinned";
import BlogList from "../components/blogList";
import Article from "../components/article";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";

const client = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl51745ug1ewz01ui5toy7p5k/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      category
      description
      content {
        html
      }
      time
      datePublished
      author {
        name
        avatar {
          url
        }
      }
      coverimg {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await client.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

const Home: NextPage = ({ posts }) => {
  console.log("props", posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog">
        <Menu />
        <Pinned />
        <BlogList posts={posts} />
        <Article />
      </div>
    </div>
  );
};

export default Home;
